### ISSUE TITLE
missing rawVal property

### ISSUE THREAD

**Issue by joprice** [vanjs-org/mini-van#11]
`rawVal` was added to van here https://github.com/vanjs-org/van/commit/8195244dc56666c1afb9838938240ea43a9035ee, but hasn't been added to mini-van. This causes shared components using `rawVal` to render `undefined` on the server.

**Comment by Tao-VanJS** [comment]
Thanks @joprice for the catch!

The issue was fixed in [0.5.7 release](https://github.com/vanjs-org/mini-van/releases/tag/0.5.7). Let me know if it works on your end.

**Comment by joprice** [comment]
Thank you! It's been working great for a while now.
