### ISSUE TITLE
Internal CSS escape characters

### ISSUE THREAD

**Issue by binhtran432k** [vanjs-org/mini-van#12]
Hi, Thank you for amazing library.

I am using mini-van for my personal portfolio and want to use style tag to optimize critical CSS loading, but I am facing the problem of auto escape html character of html in style tag `>` transpiled to `&gt;` (and `script` tag maybe also be affected) while it is valid in CSS.

I think we should add `style` tag to black list in order to not apply html escape in final output.

**Comment by Tao-VanJS** [comment]
Current we have a special handling for `script` tag. I can add `style` tag to the special handling as well.

**Comment by Tao-VanJS** [comment]
FYI, Mini-Van `0.6.1` was just released, which stops escaping for `style` tag in van-plate.
