### ISSUE TITLE
Can van-plate.d.ts work standalone?

### ISSUE THREAD

**Issue by user451421541757324** [vanjs-org/mini-van#13]
I really love the "minimalist" philosophy of your project, so I tried using Van _without npm_ with Bun.

Made a directory with two files:

- van-plate.d.ts
- app.ts

van-plate.d.ts is just [van-plate.d.ts](https://github.com/vanjs-org/mini-van/blob/main/src/van-plate.d.ts) and app.ts is just
```
import van from "./van-plate.d.ts"

const {p} = van.tags;

Bun.serve({
    static: {
        "/": new Response(van.html(p('Hello.'))),
    },

    fetch(req) {
        return new Response(null, { status: 404 });
    },
});
```
However I'm getting this error after running `bun run app.ts`:

![image](https://github.com/user-attachments/assets/86523693-ad89-4377-9be5-f35ac629c176)

I am a newbie with TypeScript/JavaScript so forgive me if this is a trivial error.

**Comment by user451421541757324** [comment]
This way it works perfectly, but then what is the purpose of van-plate.d.ts?

I deleted it (the file) and Van still works the same.

**Comment by Tao-VanJS** [comment]
`d.ts` file is for providing the type information for the `.js` file you import, which helps TypeScript to do type checking.

**Comment by user451421541757324** [comment]
Understood, thank you very much!
