### ISSUE TITLE
Missing types for 'mini-van-plate/van-plate'?

### ISSUE THREAD

**Issue by devalberg** [vanjs-org/mini-van#2]
I'm testing out the `mini-van-plate/van-plate` to create a basic text template on a minimal CodeSandbox instance but I am getting:

![image](https://github.com/vanjs-org/mini-van/assets/26262489/422e67f7-1a09-422b-ae3e-cf0d3ff1c506)

Therefore the usage:

![image](https://github.com/vanjs-org/mini-van/assets/26262489/8db24a19-937a-4abe-aeb5-96dbd77bb552)

Not sure if I have the `tsconfig` setup incorrectly or that the type declarations are simply missing. I do get the types when importing `mini-van-plate` though:

![image](https://github.com/vanjs-org/mini-van/assets/26262489/6d0b249d-a999-4213-bb0b-909d64a96ab8)

And in the usage:

![image](https://github.com/vanjs-org/mini-van/assets/26262489/be1ea022-3965-4785-afb4-d835285cd871)

## Setup

`tsconfig.json`:

```json
{
  "include": [
    "./src/*"
  ],
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ES2020"],
    "esModuleInterop": true,
    "moduleResolution": "node",
    "allowJs": true
  }
}
```

`package.json`:

```tsx
{
  "name": "node-ts-playground",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.ts",
  "scripts": {
    "start": "nodemon --exec ts-node --esm src/index.ts"
  },
  "dependencies": {
    "@types/node": "14.11.2",
    "jsdom": "21.1.1",
    "mini-van-plate": "^0.3.9",
    "ts-node": "^10.9.1",
    "typescript": "5.0.2"
  },
  "devDependencies": {
    "nodemon": "2.0.0"
  },
  "keywords": [],
  "type": "module"
}
```

ps. Love what you're doing with vanjs!

**Comment by Tao-VanJS** [comment]
I just got the same issue today. I guess changing `moduleResolution` from `node` to `bundler` would make it work. Let me know if it helps :-)

**Comment by devalberg** [comment]
However when I do this import TS stops complaining:

![image](https://github.com/vanjs-org/mini-van/assets/26262489/b57b1b66-bfb0-41fe-acb6-2fa807720063)

but of course fails to run:

```
/project/sandbox/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:380
  throw new ERR_PACKAGE_PATH_NOT_EXPORTED(
        ^
CustomError: ERR_PACKAGE_PATH_NOT_EXPORTED /project/sandbox/node_modules/mini-van-plate/ ./src/van-plate /project/sandbox/src/index.ts
    at throwExportsNotFound (/project/sandbox/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:380:9)
    at packageExportsResolve (/project/sandbox/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:605:3)
    at packageResolve (/project/sandbox/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:746:14)
    at moduleResolve (/project/sandbox/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:798:18)
    at Object.defaultResolve (/project/sandbox/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /project/sandbox/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/project/sandbox/node_modules/ts-node/src/esm.ts:168:34)
    at /project/sandbox/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/project/sandbox/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/project/sandbox/node_modules/ts-node/src/esm.ts:197:12)
```

**Comment by Tao-VanJS** [comment]
In my experiment, having either `node16` or `bundler` for `moduleResolution` would make it work. But having `node` won't work. I figured out the reason is that the old `node` version doesn't support [subpath exports](https://nodejs.org/api/packages.html#subpath-exports).

I don't have a good idea about what was happening on your side. Are you able to share the path of your repo so I can see what would happen on my end?

**Comment by devalberg** [comment]
You're right, it seems like `node16` or `nodenext` does the job!

Thank you and sorry for the bother 👼 

Not sure if this is relevant, but I was looking around on subpaths exports and came across this: https://stackoverflow.com/questions/73327767/typescript-and-subpath-imports

Could this possibly "fix" this for `moduleResolution: "node"`?

i.e. including `types` export in the library's `package.json`:

```json
  "exports": {
    ".": {
      "import": "./dist/index.mjs",
      "require": "./dist/index.cjs"
    },
    "./consolidator": {
      "types": "./dist/consolidator.d.ts",
      "import": "./dist/consolidator.mjs",
      "require": "./dist/consolidator.cjs"
    },
    "./entity": {
      "types": "./dist/entity.d.ts",
      "import": "./dist/entity.mjs",
      "require": "./dist/entity.cjs"
    }
  }
```

so in this case maybe:

```json
  "exports": {
    ".":  "./src/mini-van.js",
    "./van-plate":  {
      "import": "./src/van-plate.js",
      "export": "./src/van-plate.js",
      "types":"./src/van-plate.d.ts",
   }
```

I have no experience in this but hopefully it's something! 🤷

**Comment by Tao-VanJS** [comment]
😀 Glad the issue was resolved on your side. The suggestion in the link is to export the [CommonJS](https://nodejs.org/api/modules.html) package type along with the [ES modules](https://nodejs.org/api/esm.html). CommonJS is a package type that is primary used in older NPM packages. Currently there is no plan in the VanJS project for the CommonJS compatibility. Users are encouraged to use the more modern package type - ES modules.

**Comment by devalberg** [comment]
Ah my bad, I'll close this since it has been resolve 👍
