### ISSUE TITLE
Stream rather than concat string?

### ISSUE THREAD

**Issue by jon49** [vanjs-org/mini-van#3]
I think your project is really neat. And was looking into the code. I noticed for the back end you concatenate a lot of strings. I noticed when I was doing it that way that there was a perceivable performance hit (I guess concatenating strings is supposed to use a lot of CPU).

I use this in my personal projects for my "back end" in service workers and thought it might give you some inspiration if you are interested. It uses function generators to stream the strings to the browser instead of concatenating.

https://github.com/jon49/html-template-tag-async

**Comment by Tao-VanJS** [comment]
Hi @jon49,

Thanks for your feedback! Could you share a little bit more details about the performance hit that you have experienced?

**Comment by jon49** [comment]
I was using https://github.com/AntonioVdlC/html-template-tag and I regularly noticed a stutter on page load when using a service worker when I used it. But when I switched to the streaming one, that I created, the stutter went away. I know that isn't very scientific and more anecdotal. But it seems to make sense.

**Comment by Tao-VanJS** [comment]
Thanks for your input! In theory, stream can be more efficient than string concatenation. However, without a good benchmark methodology, it's really hard to tell whether the difference is negligible, cuz it really depends on the implementation details of the JavaScript runtime we're using.

My anecdotal experience while I was submitting the benchmark result for VanJS (https://github.com/krausest/js-framework-benchmark/pull/1353) is: I tried a few optimization techniques which I felt that might be helpful but none of them has led to statistically significant difference.

Thus I will probably wait to see if there is a good way to measure it before making the decision on whether we want to change the implementation (it will be likely a breaking change, thus we gotta be careful).

btw: if you do experience performance hit in [van-plate mode](https://vanjs.org/minivan#npm-van-plate), you can try [mini-van mode](https://vanjs.org/minivan#npm-mini-van) to see if it helps.

**Comment by jon49** [comment]
I'll make a comparison between the two. It might take a month before I get it done though.

**Comment by jon49** [comment]
Well, I did the comparison. Concatenation won over streaming doing an end-to-end test over the creation of over 1000 todos. I find it surprising. But I can't argue with the data.

Thanks for entertaining this idea.

The results, approximate:

3:26 for streaming and 2:39 for concat.

**Comment by Tao-VanJS** [comment]
Thanks @jon49 so much for the data points!

**Comment by Tao-VanJS** [comment]
btw: in `0.5.0` [release](https://github.com/vanjs-org/mini-van/releases/tag/0.5.0), we optimized the van-plate mode by reducing string concatenations and saw ~10% improvement on performance for webpages with typical complexity. You can refer to the [benchmark result](https://github.com/vanjs-org/mini-van/tree/main/bench) for details.
