### ISSUE TITLE
not able to import mini-van-plate/van-plate in bun

### ISSUE THREAD

**Issue by koladilip** [vanjs-org/mini-van#4]
this gives the following error:
`Cannot find module 'mini-van-plate/van-plate' or its corresponding type declarations.ts(2307)`

**Comment by Tao-VanJS** [comment]
See https://github.com/vanjs-org/mini-van/issues/2#issuecomment-1701978240 for the solution.

**Comment by koladilip** [comment]
Working with bundler option thanks for the quick reply.
