### ISSUE TITLE
nodenext file resolution: Type error TS2307   Cannot find module 'mini-van-plate/van-plate' or its corresponding type declarations.

### ISSUE THREAD

**Issue by btakita** [vanjs-org/mini-van#9]
When importing `mini-van-plate/van-plate` from a package with the `tsconfig.json`:

```json
{
	"compileOnSave": true,
	"compilerOptions": {
		"module": "ESNext",
		"moduleResolution": "nodenext",
		"target": "ESNext",
		"strict": true
	},
	"exclude": [
		"node_modules"
	],
	"references": []
}
```

The following error occurs:

```
Type error TS2307
  Cannot find module 'mini-van-plate/van-plate' or its corresponding type declarations.
```

See the [workaround](https://github.com/microsoft/TypeScript/issues/33079#issuecomment-738033267) to resolve this issue. As far as I know, it's the simpler one of two solutions. Basically, you have to have the source files in the root directory (no `src/` directory), add `files:` to `package.json`, & have `"moduleResolution": "nodenext"` in `tsconfig.json`.

**Comment by Tao-VanJS** [comment]
Similar issue were raised (#2, #4) before. I think https://github.com/vanjs-org/mini-van/issues/2#issuecomment-1701978240 is the solution.
